export const ADD_TODO = "ADD_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const CHANGE_FILTER = "CHANGE_FILTER"
export const LOADING = "LOADING"
export const DELETE = "DELETE"
export const DISABLED = "DISABLED"